export const STOCK_SYMBOLS = [
  { symbol: "AAPL", name: "Apple Inc." },
  { symbol: "MSFT", name: "Microsoft Corp." },
  { symbol: "GOOGL", name: "Alphabet Inc." },
  { symbol: "AMZN", name: "Amazon.com Inc." },
  { symbol: "NVDA", name: "NVIDIA Corp." },
  { symbol: "META", name: "Meta Platforms" },
  { symbol: "TSLA", name: "Tesla Inc." },
  { symbol: "JPM", name: "JPMorgan Chase" },
  { symbol: "V", name: "Visa Inc." },
  { symbol: "UNH", name: "UnitedHealth Group" },
  { symbol: "JNJ", name: "Johnson & Johnson" },
  { symbol: "WMT", name: "Walmart Inc." },
  { symbol: "XOM", name: "Exxon Mobil" },
  { symbol: "MA", name: "Mastercard Inc." },
  { symbol: "PG", name: "Procter & Gamble" },
  { symbol: "HD", name: "Home Depot" },
  { symbol: "COST", name: "Costco Wholesale" },
  { symbol: "AVGO", name: "Broadcom Inc." },
  { symbol: "NFLX", name: "Netflix Inc." },
  { symbol: "DIS", name: "Walt Disney Co." },
];

export const CRYPTO_IDS = [
  { id: "bitcoin", symbol: "BTC", name: "Bitcoin" },
  { id: "ethereum", symbol: "ETH", name: "Ethereum" },
  { id: "binancecoin", symbol: "BNB", name: "BNB" },
  { id: "ripple", symbol: "XRP", name: "XRP" },
  { id: "solana", symbol: "SOL", name: "Solana" },
  { id: "cardano", symbol: "ADA", name: "Cardano" },
  { id: "dogecoin", symbol: "DOGE", name: "Dogecoin" },
  { id: "polkadot", symbol: "DOT", name: "Polkadot" },
  { id: "avalanche-2", symbol: "AVAX", name: "Avalanche" },
  { id: "chainlink", symbol: "LINK", name: "Chainlink" },
  { id: "tron", symbol: "TRX", name: "TRON" },
  { id: "litecoin", symbol: "LTC", name: "Litecoin" },
  { id: "uniswap", symbol: "UNI", name: "Uniswap" },
  { id: "stellar", symbol: "XLM", name: "Stellar" },
  { id: "pepe", symbol: "PEPE", name: "Pepe" },
];

export const COMMODITY_SYMBOLS = [
  { symbol: "GC=F", name: "Gold", displaySymbol: "GOLD" },
  { symbol: "SI=F", name: "Silver", displaySymbol: "SILVER" },
  { symbol: "CL=F", name: "Crude Oil WTI", displaySymbol: "OIL" },
  { symbol: "BZ=F", name: "Brent Crude", displaySymbol: "BRENT" },
  { symbol: "NG=F", name: "Natural Gas", displaySymbol: "NATGAS" },
  { symbol: "HG=F", name: "Copper", displaySymbol: "COPPER" },
  { symbol: "PL=F", name: "Platinum", displaySymbol: "PLAT" },
  { symbol: "PA=F", name: "Palladium", displaySymbol: "PALLAD" },
];

export const FOREX_PAIRS = [
  { symbol: "EURUSD=X", name: "EUR/USD", displaySymbol: "EUR/USD" },
  { symbol: "GBPUSD=X", name: "GBP/USD", displaySymbol: "GBP/USD" },
  { symbol: "USDJPY=X", name: "USD/JPY", displaySymbol: "USD/JPY" },
  { symbol: "USDCHF=X", name: "USD/CHF", displaySymbol: "USD/CHF" },
  { symbol: "AUDUSD=X", name: "AUD/USD", displaySymbol: "AUD/USD" },
  { symbol: "USDCAD=X", name: "USD/CAD", displaySymbol: "USD/CAD" },
  { symbol: "NZDUSD=X", name: "NZD/USD", displaySymbol: "NZD/USD" },
  { symbol: "EURGBP=X", name: "EUR/GBP", displaySymbol: "EUR/GBP" },
  { symbol: "EURJPY=X", name: "EUR/JPY", displaySymbol: "EUR/JPY" },
  { symbol: "GBPJPY=X", name: "GBP/JPY", displaySymbol: "GBP/JPY" },
];
